website/auth.py
from flask import (
    Flask,
    Blueprint,
    request,
    session,
    render_template,
    flash,
    redirect,
    url_for,
)
import MySQLdb
import base64
from database import MySQL
from itsdangerous import URLSafeTimedSerializer
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

app = Flask(__name__)

GMAIL_USER = "itriagri@gmail.com"
GMAIL_PASSWORD = "bqhx kmok ddma uvyc"

mysql = MySQL(app)
auth = Blueprint("auth", __name__)


@auth.route("/get-started")
def getstarted():
    if session.get("logged_in"):
        return redirect(url_for("views.dashboard"))
    else:
        return redirect(url_for("auth.login"))


@auth.route("/login", methods=["GET", "POST"])
def login():

    if (request.method == "POST"):
        email = request.form["emailText"]
        password = request.form["passwordText"]

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute(
            "SELECT * FROM users WHERE email = %s AND password = %s", (email, password,),)
        user = cursor.fetchone()

        if user:

            verified = user["email_verified"]

            if verified == 0:
                send_verification_email(email)
                error = "Please verify your email. A verification email has been sent."
                return redirect(url_for("auth.login", error=error))
            else:
                session["logged_in"] = True
                session["id"] = user["id"]
                session["email"] = user["email"]
                session["fname"] = user["first_name"]
                session["mname"] = user["middle_name"]
                session["lname"] = user["last_name"]
                session["fullname"] = (f"{user['first_name']} {user['middle_name'] + ' ' if user['middle_name'] else ''}{user['last_name']}"
                                       )
                session["role"] = user["roles"]
                return redirect(url_for("views.dashboard"))

        else:
            error = "Incorrect Email or Password"
            return render_template("login.html", error=error)

    return render_template("login.html")


def generate_verification_token(email):
    serializer = URLSafeTimedSerializer(
        app.config['SECRET_KEY'], "email-verification")
    return serializer.dumps(email, salt="email-verification")


def confirm_verification_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(
        app.config['SECRET_KEY'], "email-verification")
    try:
        email = serializer.loads(
            token, salt="email-verification", max_age=expiration)
    except Exception as e:
        return False
    return email


def send_verification_email(user_email):
    token = generate_verification_token(user_email)
    verification_url = url_for(
        'auth.verify_email', token=token, _external=True)

    msg = MIMEMultipart()
    msg['From'] = GMAIL_USER
    msg['To'] = user_email
    msg['Subject'] = "Please verify your email address"

    body = f"Click the link to verify your email: {verification_url}"
    msg.attach(MIMEText(body, 'plain'))

    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.login(GMAIL_USER, GMAIL_PASSWORD)

    try:
        server.sendmail(GMAIL_USER, user_email, msg.as_string())
        server.quit()
        message = "Password reset email sent."
    except Exception as e:
        error = f"Failed to send email: {str(e)}"


@auth.route("/verify/<token>", methods=["GET", "POST"])
def verify_email(token):
    error = None
    success = None
    try:
        email = confirm_verification_token(token)
    except:
        error = "The email verification link is invalid or has expired."

    if email:
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        verified_true = 1
        cursor.execute(
            "UPDATE users SET email_verified = %s WHERE email = %s", (verified_true, email,))
        mysql.connection.commit()
        success = "Your email has been verified!"
        return redirect(url_for('auth.login', success=success))
    else:
        error = "The verification link is invalid or has expired."
        return redirect(url_for('auth.signup', error=error))


@auth.route("/signup", methods=["POST", "GET"])
def signup():
    if (
        request.method == "POST"
        and "emailText" in request.form
        and "passwordText" in request.form
    ):
        fname = request.form["fnameText"]
        mname = request.form["mnameText"]
        lname = request.form["lnameText"]
        email = request.form["emailText"]
        password = request.form["passwordText"]
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute("SELECT * FROM users WHERE email = %s", (email,))
        checkEmail = cursor.fetchone()

        if checkEmail:
            error = "Email already exists!"
            return render_template("signup.html", error=error)
        else:
            insertcursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            insertcursor.execute(
                "INSERT INTO users (first_name, middle_name, last_name, email, password) VALUES (%s, %s, %s, %s, %s)",
                (
                    fname,
                    mname,
                    lname,
                    email,
                    password,
                ),
            )
            mysql.connection.commit()
            send_verification_email(email)
            success = "Account created successfully, A verification email has been sent to your inbox!"
            return redirect(url_for("auth.login", success=success))

    return render_template("signup.html")


@auth.route("/logout")
def logout():
    session.clear()
    response = redirect("/")
    response.set_cookie("session", "", expires=0)  # Expire the session cookie
    return response


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(
        app.config["SECRET_KEY"], "password-reset")
    return serializer.dumps(email, salt="password-reset")


def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(
        app.config["SECRET_KEY"], "password-reset")
    try:
        email = serializer.loads(
            token, salt="password-reset", max_age=expiration)
    except:
        return False
    return email


@auth.route("/forgot-password", methods=["POST", "GET"])
def forgotpassword():
    message = None
    error = None
    if request.method == "POST":
        email = request.form["email"]
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute("SELECT * FROM users WHERE email = %s", (email,))
        checkEmail = cursor.fetchone()

        if checkEmail:
            token = generate_confirmation_token(email)
            confirm_url = url_for("auth.reset_password",
                                  token=token, _external=True)

            msg = MIMEMultipart()
            msg["From"] = GMAIL_USER
            msg["To"] = email
            msg["Subject"] = "Password Reset Request"

            body = (
                f"You are receiving this email because you requested a password reset for your account.\n\n"
                f"Please click on the following link to reset your password:\n\n"
                f"{confirm_url}\n\n"
                f"If you did not request a password reset, please ignore this email."
            )
            msg.attach(MIMEText(body, "plain"))


            server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
            server.login(GMAIL_USER, GMAIL_PASSWORD)

            try:
                server.sendmail(GMAIL_USER, email, msg.as_string())
                server.quit()
                message = "Password reset email sent."
            except Exception as e:
                error = f"Failed to send email: {str(e)}"
        else:
            error = "Email address not found."
        return render_template("forgot.html", error=error, success=message)

    return render_template("forgot.html", error=error, success=message)


@auth.route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    message = None
    error = None
    try:
        email = confirm_token(token)
    except:
        error = "The password reset link is invalid or has expired."

    if request.method == "POST":
        new_password = request.form["passwordText"]

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute("SELECT * FROM users WHERE email = %s", (email,))
        checkEmail = cursor.fetchone()
        if checkEmail:
            cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            cursor.execute(
                "UPDATE users SET password = %s WHERE email = %s", (new_password, email,))
            mysql.connection.commit()  # Commit the changes to the database
            message = "Password updated successfully!"
            return redirect(url_for("auth.login", success=message, error=error))
        else:
            error = "Invalid user."

    return render_template("resetpassword.html", success=message, error=error, token=token)

website/templates/addusers.html
{% extends "base.html" %} 

{% block title %}

<title>Add Users - ITRI</title>

{% endblock %}


{% block content %}

{% include "sidenav.html" %}

<main id="main" class="main">
  <div class="pagetitle">
    <h1>Add Administrator</h1>


  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <span class="invisible">NANASHI WAS HERE</span>
          {% if error %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% elif success %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ success }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endif %}
          <form action="{{ url_for('views.addusers') }}" method="POST" class="validate">
            <div class="mb-3">
              <label for="fname" class="form-label">First Name</label>
              <input type="text" class="form-control" name="fname" required></input>
            </div>

            <div class="mb-3">
              <label for="mname" class="form-label">Middle Name</label>
              <input type="text" class="form-control" name="mname" required></input>
            </div>

            <div class="mb-3">
              <label for="lname" class="form-label">Last Name</label>
              <input type="text" class="form-control" name="lname" required></input>
            </div>

            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" name="email" required></input>
            </div>

            <div class="mb-3">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" name="password" required></input>
            </div>



            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>



{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />

  {% block title %} Nikko {% endblock %}


  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect" />
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />

  <link href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" rel="stylesheet">
  



  <link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet" />
  <!-- Vendor CSS Files -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet" />
  <!-- Main CSS File -->
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet" />
  <link href="{{url_for('static', filename='css/dashboard.css')}}" rel="stylesheet" />
</head>

<body>


  {% block content %} Nikko {% endblock %}

  <main id="main" class="main">



  </main>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
   

  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/aos/aos.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/imagesloaded/imagesloaded.pkgd.min.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>
  <!-- Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js')}}"></script>
  <script src="{{ url_for('static', filename='js/dashboard.js')}}"></script>
  <!-- Custom JS File -->
  <!-- <script src="{{ url_for('static', filename='js/custom.js')}}"></script> -->
  

</body>

</html>

website/templates/forgot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Forgot Passsword - ITRI</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">
    <!-- Main CSS File -->
    <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">
</head>

<body class="login-page">
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
            <a href="/" class="logo d-flex align-items-center">
                <h1 class="sitename">ITRI</h1>
            </a>
            <nav id="navmenu" class="navmenu">
                <ul>
                    <li>
                        <a href="/#hero" class="active">Home</a>
                    </li>
                    <li>
                        <a href="/#about">About</a>
                    </li>
                    <li>
                        <a href="/#insect">Insects</a>
                    </li>
                    <li>
                        <a href="/login#signin">Login</a>
                    </li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>
        </div>
    </header>
    <main class="main">
        <section id="signin" class="hero section dark-background">
            <img src="{{ url_for('views.serve_image', filename='bg1.webp') }}" alt="Hero Background">
            <div class="container" data-aos="fade-up" data-aos-delay="100">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-header text-center">
                                <h3 class="text-success">Forgot Password</h3>
                                {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                                {% elif success %}
                                <div class="alert alert-success" role="alert">
                                    {{ success }}
                                </div>
                                {% endif %}
                            </div>
                            <div class="card-body p-5">
                                <form action="{{ url_for('auth.forgotpassword') }}" method="POST">
                                    <div class="mb-3">
                                        <label class="form-label">Email address</label>
                                        <input type="email" class="form-control border border-dark" id="email"
                                            aria-describedby="emailHelp" name="email" required>
                                    </div>
                                    <div class="mb-3 form-check text-center">
                                        <button type="submit" class="w-75 btn-login">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>
    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/aos.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/imagesloaded/imagesloaded.pkgd.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>
    <!-- Main JS File -->
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
</body>

</html>

website/templates/history.html
{% extends "base.html" %} 

{% block title %}

<title>History - ITRI</title>

{% endblock %}


{% block content %}

{% include "sidenav.html" %}



<main id="main" class="main">
  <div class="pagetitle">
    <div class="row col-sm-12">
      <div class="col-sm-6">
        <h1>Search History</h1>
      </div>
      <div class="col-sm-6 d-flex justify-content-end">
        <button onclick="window.print()" class="btn btn-primary">Print</button> &nbsp;
        <!-- <button id="print" class="btn btn-primary">PDF</button> -->
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 row d-flex justify-content-center">
      <div class="col-sm-6">
        <canvas id="history_chart" height="350"></canvas>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <span class="invisible">NANASHI WAS HERE</span>

          <table id="history" class="table table-striped display" style="width: 100%">
            <thead>
              <tr>
                <th scope="col">Insect Name</th>
                <th scope="col">Image</th>
                <th scope="col">Date</th>
                <th scope="col">User</th>
              </tr>
            </thead>
            <tbody>
              {% for h in history %}
              <tr>
                <td>{{ h['insect_name'] }}</td>
                <td>
                  {% if h['insect_image'] %}
                  <img src="data:image/jpeg;base64,{{ h['insect_image'] }}" alt="Insect Image" class="insect-image"
                    loading="lazy" width="100" height="100">
                  {% else %}
                  <img src="{{ url_for('static', filename='img/placeholder.png')}}" alt="Placeholder Image"
                    class="insect-image" loading="lazy" width="100" height="100">
                  {% endif %}
                </td>
                <td>{{ h['date'] }}</td>
                <td>{{ h['fullname'] }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>

</main>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{{ url_for('static', filename='js/jquery-3.7.1.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>
<script src="{{ url_for('static', filename='js/dataTables.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>





<script>
  const chartData = JSON.parse('{{ chart_data|tojson|safe }}');
  console.log("Parsed chartData:", chartData);

  $(document).ready(function () {
    $('#history').DataTable({
      paging: true,
      pageLength: 10,
      pagingType: 'full',
      order: [],
      responsive: true
    });
  });

  if (chartData && chartData.labels.length > 0 && chartData.data.length > 0) {
    const ctx = document.getElementById('history_chart').getContext('2d');




    const myChart = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: chartData.labels,
        datasets: [{
          label: 'Insect Search Frequency',
          data: chartData.data,
          borderWidth: 3
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          datalabels: {
            color: '#fff',
            formatter: (value, context) => {
              const total = context.chart.data.datasets[0].data.reduce((acc, val) => acc + val, 0);
              const percentage = ((value / total) * 100).toFixed(2);
              return `${percentage}%`;
            },
            font: {
              weight: 'bold',
              size: 10,
            },
          },
          tooltip: {
            callbacks: {
              label: function (context) {
                const total = context.dataset.data.reduce((acc, value) => acc + value, 0);
                const value = context.raw;
                const percentage = ((value / total) * 100).toFixed(2);
                return `${context.label}: ${value} (${percentage}%)`;
              }
            }
          },
          legend: {
            position: 'bottom',
          },
          title: {
            display: true,
            text: 'Search Frequency Percentage Chart'
          }
        }
      },
      plugins: [ChartDataLabels]
    });
  } else {

    const historyChart = document.getElementById('history_chart');
    // Handle the case where the data is empty (e.g., display a message)
    historyChart.style.height = '0px';

  }
</script>

<!-- <script>


  document.addEventListener("DOMContentLoaded", () => {
    let printLink = document.getElementById("print");
    let container = document.getElementById("main");

    printLink.addEventListener("click", event => {
      event.preventDefault();
      printLink.style.display = "none";
      window.print();
    }, false);

    container.addEventListener("click", event => {
      printLink.style.display = "flex";
    }, false);

  }, false);
</script> -->






{% endblock %}

website/templates/insectrequest.html
{% extends "base.html" %} {% block title %} Rice Something {% endblock %} {%
block content %} {% include "sidenav.html" %}

<main id="main" class="main">
  <div class="pagetitle">
    <h1>Request Insect</h1>

  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <span class="invisible">NANASHI WAS HERE</span>
          {% if error %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ error }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% elif success %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ success }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
          {% endif %}
          
          <form action="{{ url_for('views.insectrequest') }}" method="POST" enctype="multipart/form-data"
            class="required" nonvalidate>
            <div class="mb-3">
              <label for="insectnameText" class="form-label">Insect Name</label>
              <input type="text" class="form-control" id="insectnameText" name="insectnameText" required />
            </div>

            <div class="mb-3">
              <label for="descriptionText" class="form-label">Description (Optional)</label>
              <input type="text" class="form-control" id="descriptionText" name="descriptionText"/>
            </div>

            <div class="mb-3">
              <label for="insectImage" class="form-label">Insect Image (Optional)</label>
              <input class="form-control" type="file" name="insectImage" id="insectImage">
            </div>

            <input type="number" class="form-control" id="useridText" name="useridText" value="{{ session['id'] }}"
              style="display: none" />
            <div class="mb-3 text-center">
              <button type="submit" class="btn btn-outline-primary w-25">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

website/templates/requests.html
{% extends "base.html" %} {% block title %} Rice Something {% endblock %} {%
block content %} {% include "sidenav.html" %}

<main id="main" class="main">
  <div class="pagetitle">
    <h1>Requested Insect</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <span class="invisible">NANASHI WAS HERE</span>

          <table id="request" class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Insect Name</th>
                <th scope="col">Description</th>
                <th scope="col">Requester</th>
                <th scope="col">Image</th>
              </tr>
            </thead>
            <tbody>
              {% for request in requests %}
              <tr>
                <td>{{ request['request_id'] }}</td>
                <td>{{ request['insect_name'] }}</td>
                <td>{{ request['description'] }}</td>
                <td>{{ request['fullname'] }}</td>
                <td>
                  {% if request['insect_image'] %}
                      <img src="data:image/jpeg;base64,{{ request['insect_image'] }}" alt="Insect Image" style="height:100px; width: 100px; object-fit: cover;">
                  {% else %}
                      N/A
                  {% endif %}
              </td>
              
              </tr>
              {% else %}
              <tr class="text-center">
                <td colspan="5">No Records Found</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  
</main>

<script src="{{ url_for('static', filename='js/jquery-3.7.1.js')}}"></script>
<script src="{{ url_for('static', filename='js/dataTables.js')}}"></script>

<script>
  new DataTable('#request', {
    search: {
      return: true
    },
    responsive: true
  });

</script>

{% endblock %}

website/templates/staff.html
{% extends "base.html" %} 

{% block title %}

<title>Staffs - ITRI</title>

{% endblock %}


{% block content %}

{% include "sidenav.html" %}
    <main id="main" class="main">
      <div class="pagetitle">
        <h1>Model Settings</h1>
      </div>
    
      <div class="row mb-3">
        <div class="col-sm-12">
          
        </div>
    
      </div>
    
    
    
    </main>
    
    
    
    {% endblock %}